#!/bin/bash
# Raven HTML Report Generator
# Converts mission summary + executive digests into a styled HTML report

if [ -z "$1" ]; then
    echo "Usage: $0 <CASE_NAME>"
    exit 1
fi

CASE=$1
CASE_DIR="/mnt/GhostRaven/09📑Evidence/$CASE/hybrid"

if [ ! -d "$CASE_DIR" ]; then
    echo "❌ Case directory not found: $CASE_DIR"
    exit 1
fi

# Find the latest mission summary
SUMMARY=$(ls -t "$CASE_DIR"/mission_summary_*.txt 2>/dev/null | head -n 1)

if [ -z "$SUMMARY" ]; then
    echo "❌ No mission summary found in $CASE_DIR"
    exit 1
fi

HTML_REPORT="$CASE_DIR/mission_summary_$(date +%Y%m%d_%H%M%S).html"

echo "=============================="
echo " 🦅 Generating HTML Report"
echo " Case: $CASE"
echo " Source: $SUMMARY"
echo " Output: $HTML_REPORT"
echo "=============================="

# Build HTML
{
cat <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Raven Mission Report - $CASE</title>
<style>
body { font-family: Arial, sans-serif; margin: 40px; background: #f4f4f4; color: #222; }
h1 { color: #2c3e50; }
h2 { color: #34495e; border-bottom: 2px solid #ccc; padding-bottom: 4px; }
pre { background: #fff; padding: 10px; border: 1px solid #ccc; overflow-x: auto; }
.section { margin-bottom: 30px; }
.footer { font-size: 0.9em; color: #555; margin-top: 40px; }
</style>
</head>
<body>
<h1>🦅 Raven Mission Report</h1>
<div class="section">
<h2>Case Information</h2>
<p><strong>Case:</strong> $CASE<br>
<strong>Date Generated:</strong> $(date)</p>
</div>
EOF

# Parse mission summary into sections
awk '
/^ 📑 Executive Summary:/ {
    if (section_open) { print "</pre></div>" }
    section_open=1
    title=substr($0,5)
    print "<div class=\"section\"><h2>" title "</h2><pre>"
    next
}
{ if (section_open) print }
END { if (section_open) print "</pre></div>" }
' "$SUMMARY"

cat <<EOF
<div class="footer">
<p>Generated by Raven Hybrid Module<br>
Evidence stored in: $CASE_DIR</p>
</div>
</body>
</html>
EOF
} > "$HTML_REPORT"

echo "✅ HTML report created: $HTML_REPORT"
